name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # Use appropriate version
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test
